services:
  order-service:
    build:
      context: .  # The root directory containing all projects
      dockerfile: src/OrderService/OrderService.API/Dockerfile
    container_name: order-service
    ports:
      - "5066:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=order-db;Database=OrderDB;Username=postgres;Password=yourpassword
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - order-db
      - rabbitmq

  stock-service:
    build:
      context: .  # The root directory containing all projects
      dockerfile: src/StockService/StockService.API/Dockerfile
    container_name: stock-service
    ports:
      - "5067:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=stock-db;Database=StockDB;Username=postgres;Password=yourpassword
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - stock-db
      - rabbitmq

  notification-service:
    build: 
      context: .
      dockerfile: src/NotificationService/NotificationService.API/Dockerfile
    container_name: notification-service
    ports:
      - "5065:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=notification-db;Database=NotificationDB;Username=postgres;Password=yourpassword
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - notification-db
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  order-db:
    image: postgres:13
    container_name: order-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=OrderDB
    ports:
      - "5433:5432"

  stock-db:
    image: postgres:13
    container_name: stock-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=StockDB
    ports:
      - "5434:5432"

  notification-db:
    image: postgres:13
    container_name: notification-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=NotificationDB
    ports:
      - "5435:5432"
