@OrderService.API_HostAddress = http://localhost:5066

POST http://localhost:5066/api/v1/order
Content-Type: application/json

{
  "customerId": "3f6cbc83-56ec-450b-b228-97f00539348f",
  "orderItems": [
    {
      "productId": "737186b5-e62c-4329-a64c-a4386fbdc6d7",
      "quantity": 10,
      "unitPrice": 30.99
    }
  ]
}

###

GET http://localhost:5066/api/v1/order/0195fd1e-c64c-77d9-b3b3-8bbcb9940b8b
Content-Type: application/json
