@OrderService.API_HostAddress = http://localhost:5066

POST http://localhost:5066/api/v1/order
Content-Type: application/json

{
  "customerId": "3f6cbc83-56ec-450b-b228-97f00539348f",
  "orderItems": [
    {
      "productId": "97f00539-450b-b228-56ec-3f6cbc83348f",
      "quantity": 3,
      "unitPrice": 10.5
    }
  ]
}

###

GET http://localhost:5066/api/v1/order/0195fc7b-0945-759a-8c79-0059888ac99d
Content-Type: application/json
